Repository player-ui/devtools-assets, pull requests merged in 2024-04, with the labels that each got.

#14 Docs/devtools site
  docs/site/.eslintrc.json
  docs/site/.gitignore
  docs/site/README.md
  docs/site/components/ColorSchemeSwitch.tsx
  docs/site/components/Context.tsx
  docs/site/components/DevtoolsTeam.tsx
  docs/site/components/Image.tsx
  docs/site/components/Navigation.tsx
  docs/site/components/chakra-theme.ts
  docs/site/components/code-highlight/index.tsx
  docs/site/components/code-highlight/prism-colors.ts
  docs/site/components/gh-icon.tsx
  docs/site/components/mdx-components.tsx
  docs/site/components/mdx-layout.tsx
  docs/site/config/constants.ts
  docs/site/config/navigation.ts
  docs/site/config/team.json
  docs/site/next.config.mjs
  docs/site/package.json
  docs/site/pages/_app.tsx
  docs/site/pages/assets/action.mdx
  docs/site/pages/assets/collection.mdx
  docs/site/pages/assets/console.mdx
  docs/site/pages/assets/input.mdx
  docs/site/pages/assets/list.mdx
  docs/site/pages/assets/navigation.mdx
  docs/site/pages/assets/object-inspector.mdx
  docs/site/pages/assets/stacked-view.mdx
  docs/site/pages/assets/table.mdx
  docs/site/pages/assets/text.mdx
  docs/site/pages/globals.css
  docs/site/pages/index.tsx
  docs/site/pages/overview.mdx
  docs/site/pages/page.module.css
  docs/site/pages/plugin.mdx
  docs/site/pages/team.mdx
  docs/site/public/favicon.ico
  docs/site/public/logo/logo-dark-large.png
  docs/site/public/logo/logo-dark-small.png
  docs/site/public/logo/logo-light-large.png
  docs/site/public/logo/logo-light-small.png
  docs/site/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: skip-release

#16 fix table styles
  table/src/component/index.tsx
Labels: patch

#17 feat: adds code-editor asset
  .bazelignore
  code-editor/BUILD
  code-editor/README.md
  code-editor/package.json
  code-editor/src/component/index.tsx
  code-editor/src/dsl/__tests__/index.test.tsx
  code-editor/src/dsl/index.tsx
  code-editor/src/index.ts
  code-editor/src/transform/index.ts
  code-editor/src/types/index.ts
  docs/site/pages/assets/code-editor.mdx
  docs/storybook/.storybook/preview.ts
  docs/storybook/BUILD
  docs/storybook/src/assets/CodeEditor.mdx
  docs/storybook/src/assets/CodeEditor.stories.tsx
  docs/storybook/src/flows/code-editor/basic.tsx
  docs/storybook/src/flows/devtools/basic.tsx
  docs/storybook/vite.config.ts
  package.json
  plopfile.mjs
  plugin/BUILD
  plugin/package.json
  plugin/src/index.ts
  plugin/src/plugins/AssetsRegistryPlugin.tsx
  plugin/src/plugins/TransformPlugin.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  stacked-view/src/component/index.tsx
Labels: minor
